### ISSUE TITLE
Add beginner friendly repos

### ISSUE THREAD

**Issue by vivian-dai** [vivian-dai/Hacktoberfest-2021-Repos#10]
* find some simple enough looking repositories, create a PR and add them
* if any of the repositories on the list are no longer being accepted by Hacktoberfest, remove it and add it to the excluded list

**Comment by Meghwantsingh** [comment]
Hello I am new to this but what i have to do pls tell.
And i have read what you given about Excluded Project
some of work showing Excluded Project pls. tell what to do.

**Comment by vivian-dai** [comment]
@Meghwantsingh you can add excluded projects to the [blacklist file](https://github.com/vivian-dai/Hacktoberfest-2021-Repos/blob/main/blacklist/README.md). i'm not really sure what exactly you're asking
