### ISSUE TITLE
Arrange blacklist in alphabetical order

### ISSUE THREAD

**Issue by vivian-dai** [vivian-dai/Hacktoberfest-2021-Repos#40]
Sort the blacklist contents so that it's in alphabetical order order by repository name. It would also be useful to sort the repositories/organizations in each section (table) in alphabetical order.

**Comment by akshaydhayal** [comment]
Hey,  can you assign this to me?

**Comment by vivian-dai** [comment]
@akshaydhayal  if you're still up for it you can sort the other repositories in alphabetical order too
